### PR TITLE
server.xml is now managed by accumulator

### LINKED ISSUE #34: vhosts state manages server.xml
Should the vhosts state manage the server.xml configuration?

### PR DESCRIPTION
**Pull request by fintanmm**
I've stripped out the comments from the server.xml file. The config state now manages the connector within server.xml, vhosts state manages vhosts within server.xml and the native state now enables AprLifecycleListener. 

This PR fixes #34 and #23. The config test should be broken out into separate tests but I didn't have time to do so.

### CODE REVIEW

**Comment by gravyboat** [comment]
Can you please rebase?

**Comment by fintanmm** [comment]
Yeah sure, I was waiting to see if anyone had an issue with the PR.

**Comment by gravyboat** [comment]
For sure, in the future please don't merge your own PRs. Then we can at least pretend we have some checks and balances in place.

**Comment by fintanmm** [comment]
Apologize, was in a rush. Won't happen again.

**Comment by gravyboat** [comment]
No worries it happens!

**Pull request merged**
