### PR TITLE
Initial configuration for continuous build

### PR DESCRIPTION
**Pull request by fintanmm**
Hi, 

With this PR, I'm trying to automate the build with travis. Currently the states are failing but I'm working through the failures. This PR builds on the work done by @amontalban for the mysql-formula. 
I'm not sure if having so many instances is the best way to go. Please let me know what you think?

fintan

### CODE REVIEW

**Comment by gravyboat** [comment]
This looks good to me, main concern is there are so many items in the matrix it's going to take 6 hours to run inside of Travis, but slow tests > no test!

**Comment by fintanmm** [comment]
Yeah I was thinking that @gravyboat but is there a different way to do it?

**Comment by gravyboat** [comment]
@fintanmm Not that I can think of, how you're doing it is the best possible way, we'll just have to deal with it since we're using the free version of Travis.

**Comment by fintanmm** [comment]
I tried lumping the builds into one matrix for Ubuntu, Debian and centos and it was the same. Building with VirtualBox isn't any faster I don't think. @gravyboat do you know of a way to limit what get built? Say if I modify the native state only the native instances will get built.

**Comment by gravyboat** [comment]
@fintanmm I'm not sure honestly. I have no issue with all of them running, it's going to take a bit no matter what.

**Comment by fintanmm** [comment]
Ok cool @gravyboat, do you want to leave this PR open till I can get the build issues sorted?

**Comment by gravyboat** [comment]
@fintanmm Nah I'll merge it for now. We can always fix it later.

**Pull request merged**
