### PR TITLE
added Debian 9 (stretch) support

### PR DESCRIPTION
**Pull request by edusperoni**

### CODE REVIEW

**Comment by javierbertoli** [comment]
I see [*xenial*](https://github.com/edusperoni/tomcat-formula/blob/d14c6fa5bb7b79c2160e46fbf0869f4e41c734a9/tomcat/codenamemap.yaml#L15-L28), [*jessie*]( https://github.com/edusperoni/tomcat-formula/blob/d14c6fa5bb7b79c2160e46fbf0869f4e41c734a9/tomcat/codenamemap.yaml#L42-L54)and [*stretch*](https://github.com/edusperoni/tomcat-formula/blob/d14c6fa5bb7b79c2160e46fbf0869f4e41c734a9/tomcat/codenamemap.yaml#L55-L67) they all share the same parameters. 

Why don't you rather add them in the `osmap.yml` file, in the [Debian](https://github.com/saltstack-formulas/tomcat-formula/blob/master/tomcat/osmap.yaml#L3) entry and remove these sections in the `codenamemap.yaml`, in order to remove duplications and keep it DRY?

**Comment by edusperoni** [comment]
Done :)

**Comment by javierbertoli** [comment]
Great! mind you just remove a few more lines that, I see now, are unneeded in `codenamemap.yaml` as they're in the new defaults in `osmap.yaml`?:

* `[native_pkg: libtcnative-1` is unneeded [here](https://github.com/edusperoni/tomcat-formula/blob/3d52f78b2733a7fe89c4dc4b94568c5f59d4a34d/tomcat/codenamemap.yaml#L4) and [here](https://github.com/edusperoni/tomcat-formula/blob/3d52f78b2733a7fe89c4dc4b94568c5f59d4a34d/tomcat/codenamemap.yaml#L17)
* `with_haveged: true` and `haveged_enabled: true`, [here](https://github.com/edusperoni/tomcat-formula/blob/3d52f78b2733a7fe89c4dc4b94568c5f59d4a34d/tomcat/codenamemap.yaml#L6-L7) and [here](https://github.com/edusperoni/tomcat-formula/blob/3d52f78b2733a7fe89c4dc4b94568c5f59d4a34d/tomcat/codenamemap.yaml#L19-L20). (There are also some trailing commas on the 2nd ones :smile:)
* `java_home: /usr/lib/jvm/default-java`, [here](https://github.com/edusperoni/tomcat-formula/blob/3d52f78b2733a7fe89c4dc4b94568c5f59d4a34d/tomcat/codenamemap.yaml#L14) and [here](https://github.com/edusperoni/tomcat-formula/blob/3d52f78b2733a7fe89c4dc4b94568c5f59d4a34d/tomcat/codenamemap.yaml#L27)

I think that with that, we'll be OK to merge.

**Comment by javierbertoli** [comment]
Thanks, @edusperoni !

**Comment by edusperoni** [comment]
Np :D Glad to help.

I'll probably submit another PR when I get the time. Changing the tomcat user breaks it completely, since the new user doesn't have permission to directories like /var/cache/tomcat8 and /var/log/tomcat8 (at least in Debian 9).

**Pull request merged**
