### PR TITLE
adds tests for ubuntu

### PR DESCRIPTION
**Pull request by fortune-juggle**

### CODE REVIEW

**Comment by fintanmm** [comment]
Besides the upstream bug, everything looks good. We could probably close #40 as well.

**Comment by fintanmm** [comment]
Hey @fortune-juggle, I was thinking we could do something like this in the native state for a workaround.

```
{% if grains['os'] == 'Ubuntu' %}
/usr/lib/{{grains['cpuarch']}}-linux-gnu/libtcnative-1.so:
  file.symlink:
    - target: /usr/lib/libtcnative-1.so
{% endif %}
```

What do you think?

**Comment by fintanmm** [comment]
Looks good @fortune-juggle thanks

**Comment by gravyboat** [comment]
Thanks for working together to get this done!

**Pull request merged**
