### PR TITLE
Updated kitchen tests & pass all CI jobs

### PR DESCRIPTION
**Pull request by noelmcloughlin**
This PR is fixes for kitchen tests.

### CODE REVIEW

**Comment by aboe76** [comment]
@noelmcloughlin thanks for this

**Comment by javierbertoli** [comment]
But... tests failed in this PR? :smile:

**Comment by noelmcloughlin** [comment]
Yes, can we revert? Just working on this.

**Comment by noelmcloughlin** [comment]
Actually it's fine.  The kitchen.yaml is correct now.  I opened new PR for updating integration tests: https://github.com/saltstack-formulas/tomcat-formula/pull/96

**Comment by aboe76** [comment]
@javierbertoli , I have faith in @noelmcloughlin :)

**Comment by javierbertoli** [comment]
Nothing to discuss there @aboe76, me too :smile:

**Comment by noelmcloughlin** [comment]
Thanks @javierbertoli for the reviews and @aboe76  Travis is indeed fixed now via #96 . There are still issues with getting tomcat service running on all Travis CI tests.  Some or all of the issues are caused by Java10 ??

**Pull request merged**
