### PR TITLE
fix bug in security

### PR DESCRIPTION
**Pull request by lookingcloudy**
Group name needs to be changed to allow access to admin-gui

### CODE REVIEW

**Comment by gravyboat** [comment]
I don't know enough about Tomcat to understand whether this will negatively impact something else. I'm going to leave this open until someone else comes along that has more experience with it. If it's not merged/commented on again in a day or two ping me and I'll do some research.

**Comment by aboe76** [comment]
@lookingcloudy 

in the documentation: https://tomcat.apache.org/tomcat-7.0-doc/manager-howto.html

```
You can find the role names in the web.xml file of the Manager web application. 

The available roles are:
manager-gui — Access to the HTML interface.
manager-status — Access to the "Server Status" page only.
manager-script — Access to the tools-friendly plain text interface that is described in this document, and to the "Server Status" page.
manager-jmx — Access to JMX proxy interface and to the "Server Status" page.

The HTML interface is protected against CSRF (Cross-Site Request Forgery) attacks, but the text and JMX interfaces cannot be protected. It means that users who are allowed access to the text and JMX interfaces have to be cautious when accessing the Manager application with a web browser. To maintain the CSRF protection:
If you use web browser to access the Manager application using a user that has either manager-script or manager-jmx roles (for example for testing the plain text or JMX interfaces), you MUST close all windows of the browser afterwards to terminate the session. If you do not close the browser and visit other sites, you may become victim of a CSRF attack.
It is recommended to never grant the manager-script or manager-jmx roles to users that have the manager-gui role.
```

Maybe we should make the tomcat-users.xml more pillar driven to allow more combinations?

**Comment by lookingcloudy** [comment]
aboe76 - good idea driving the users and roles from pillar.  I made this change and pushed a new version.  NOTE: I eliminated the <roles/> tag in the file.  It seems this is only used for enumeration of the available roles via API rather than useful configuration.

**Comment by aboe76** [comment]
@lookingcloudy, nice work, I really likte this but it means that the change is not backwards compatible anymore, and should be documented.

**Comment by lookingcloudy** [comment]
@aboe76 - Hopefully 3rd time is a charm!  Now backwards compatible...and a explanation blurb in the tomcat-users.xml file.

**Comment by aboe76** [comment]
@lookingcloudy, thank you, thank you, I'm sorry but this way 53 others who forked this, won't get a nasty suprise...

**Pull request merged**
